<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <DebugType>none</DebugType>
    <Version>1.0.0</Version>
    <ApplicationIcon>..\LeanBrowser\Assets\CottonBrowser.ico</ApplicationIcon>
    <AssemblyName>CottonBrowserSetup</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Payload.zip" LogicalName="CottonBrowser.Payload.zip" />
  </ItemGroup>
</Project>
